=== jimenezmunozguillermorafael/Apuntes1DAM/LM/Relación4/XML_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="colegio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "clase" minOccurs="1" maxOccurs="3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "alumno" minOccurs="1" maxOccurs="3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name = "nombre">
                                            <xs:simpleType>
                                                <xs:restriction base = "xs:string">
                                                    <xs:pattern value="[A-Z][a-z]+( [A-Z][a-z]+)*"/>

                                                </xs:restriction>
                                            </xs:simpleType>

                                        </xs:element>
                                        <xs:element name = "edad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="6"/>
                                                    <xs:maxInclusive value="18"/>
                                                    

                                                </xs:restriction>
                                            </xs:simpleType>

                                        </xs:element>
                                        <xs:element name = "nota" minOccurs="1" maxOccurs="5">
                                            <xs:simpleType>
                                                <xs:restriction base= "xs:decimal">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="10"/>
                                                    <xs:fractionDigits value="2"/>

                                                </xs:restriction>
                                            </xs:simpleType>

                                        </xs:element>
                                        <xs:element name = "dni">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{8}[A-Z]"/>

                                                </xs:restriction>

                                            </xs:simpleType>

                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                                </xs:complexType>

                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== jimenezmunozguillermorafael/Apuntes1DAM/LM/Relación4/XML_XSD.xml
<!--DiseÃ±a desde cero un XML y su XSD para un sistema escolar con estas caracterÃ­sticas:

    El documento tiene un elemento raÃ­z clase.
    La clase contiene varios alumno.
    Cada alumno tiene:
        nombre (cadena que debe empezar con mayÃºscula, regex).
        edad (entero entre 6 y 18).
        Una lista de nota (decimal entre 0 y 10, puede haber entre 1 y 5 notas).
        Un dni que siga el formato 8 dÃ­gitos + 1 letra (regex).
    El alumno debe tener un atributo id Ãºnico (entero positivo).

ðŸ‘‰ Tu tarea:

    Define el XSD.
    Escribe un XML con al menos 2 alumnos y sus notas.
-->
<?xml version="1.0" encoding="UTF-8"?>

<colegio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XML_XSD.xsd">
    <clase>
    <alumno id ="1">
        <nombre>Juan</nombre>
        <edad>26</edad>
        <nota>9.75</nota>
        <dni>23456997z</dni>       
    </alumno>
    <alumno id ="2">
        <nombre>Juan</nombre>
        <edad>26</edad>
        <nota>9.75</nota>
        <dni>23456997z</dni>    
    </alumno>
    <alumno id ="3">
        <nombre>Juan</nombre>
        <edad>26</edad>
        <nota>9.75</nota>
        <dni>23456997z</dni>        
    </alumno>
    
</clase>
    
    <clase>

    <alumno id= "4">
        <nombre>Pepe</nombre>
        <edad>24</edad>
        <nota>5</nota>
        <dni>12345678T</dni>
    </alumno>
    <alumno id ="5">
        <nombre>Juan</nombre>
        <edad>26</edad>
        <nota>9.75</nota>
        <dni>23456997z</dni>        
    </alumno>
    <alumno id ="6">
        <nombre>Juan</nombre>
        <edad>26</edad>
        <nota>9.75</nota>
        <dni>23456997z</dni>           
    </alumno>   
    
</clase>
    
    <clase>
        <alumno id ="7">
        <nombre>Juan</nombre>
        <edad>26</edad>
        <nota>9.75</nota>
        <dni>23456997z</dni>
        
    </alumno>
        <alumno id ="8">
        <nombre>Zote</nombre>
        <edad>25</edad>
        <nota>0.5</nota>
        <dni>98765432E</dni>
    </alumno>
    <alumno id ="9">
        <nombre>Juan</nombre>
        <edad>26</edad>
        <nota>9.75</nota>
        <dni>23456997z</dni>       
    </alumno>
    
</clase>
   
</colegio>
