<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso [
    <!ELEMENT curso (nombre, alumno+)> 
    <!ELEMENT alumno (nombre, apellido?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
]>
<curso>
    <nombre>Clase1</nombre>
    <alumno>
        <nombre>Guillermo</nombre>
        <apellido>Jimenez</apellido>
    </alumno>
    <alumno>
        <nombre>Rafa</nombre>
        <apellido>Perez</apellido>
    </alumno>
    <alumno>
        <nombre>Pepe</nombre>
        <apellido>Grillo</apellido>
    </alumno>
</curso>