<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipo [
  <!ELEMENT equipo (pokemon+)>
  <!ELEMENT pokemon (nombre, tipo+, nivel?)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT tipo (#PCDATA)>
  <!ELEMENT nivel (#PCDATA)>
]>
<equipo>
  <pokemon>
    <nombre>Charizard</nombre>
    <tipo>Fuego</tipo>
    <tipo>Volador</tipo>
    <nivel>42</nivel>
  </pokemon>
  <pokemon>
    <nombre>Gyarados</nombre>
    <tipo>Agua</tipo>
    <tipo>Volador</tipo>
    <nivel>38</nivel>
  </pokemon>
  <pokemon>
    <nombre>Snorlax</nombre>
    <tipo>Normal</tipo>
  </pokemon>
</equipo>